---
- name: postgresql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: create variable
  command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
  register: repo_line

- debug:
    msg: "{{ repo_line.stdout }}"

- name: add postgresql repo
  apt_repository:
    repo: "{{ repo_line.stdout }}"
    state: present
  become: true

- name: Ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql-10
    - libpq-dev
    - python-psycopg2

- name:   Ensure database is created
  become_user: postgres
  postgresql_db: name={{db_name}}

- name: Ensure user has access to database
  become_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL

- name: Ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user: name={{db_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: Ensure no other user can access the database
  become_user: postgres
  postgresql_privs: db={{db_name}} role=PUBLIC type=database priv=ALL state=absent
