---
- name: Install software for apt repository management.
  become: true
  apt:
    name: ['python3-apt', 'python3-pycurl']
    state: present

- name: Install essential packages
  apt:
    update_cache: yes
    pkg:
      - git
      - vim
      - htop
      - curl
      - unzip
      - build-essential
      - libssl-dev
    state: present
  become: true
