---

- name: Start php-fpm
  service:
    name: php{{ php_version }}-fpm
    state: started
  become: true

- name: Restart php-fpm
  service:
    name: php{{ php_version }}-fpm
    state: restarted
  become: true
